baseURL: https://edjopato.de/
DefaultContentLanguage: de
disablePathToLower: true
languageCode: de
metaDataFormat: "yaml"
paginate: 12
pygmentsCodeFences: true
pygmentsUseClasses: true
theme: edjopato-hugo-theme
title: EdJoPaTo

menu:
  main:
    - Name: "Blog"
      Identifier: "blog"
      URL: "/post/"
