baseURL: https://edjopato.de/
defaultContentLanguage: de
enableGitInfo: true
languageCode: de
metaDataFormat: "yaml"
paginate: 12
pygmentsCodeFences: true
pygmentsUseClasses: true
title: EdJoPaTo

# Helpful when sending single pages to people
# canonifyURLs: true
# relativeUrls: true

minify:
  minifyOutput: true

params:
  images:
    - /apple-touch-icon.png
  license:
    name: CC BY-ND 4.0
    url: https://creativecommons.org/licenses/by-nd/4.0/

menu:
  main: []
    # - Name: "Blog"
    #   Identifier: "blog"
    #   URL: "/post/"

server:
  headers:
    - for: /**
      values:
        Content-Security-Policy: >-
          default-src 'none';
          base-uri 'none';
          form-action 'none';
          frame-ancestors 'none';
          img-src 'self';
          manifest-src 'self';
          script-src 'self';
          style-src 'self';

          connect-src 'self';
