baseURL: https://edjopato.de/
DefaultContentLanguage: de
disablePathToLower: true
languageCode: de
metaDataFormat: "yaml"
paginate: 12
pygmentsCodeFences: true
pygmentsUseClasses: true
theme: edjopato-hugo-theme
title: EdJoPaTo

menu:
  main:
    - Name: "Blog"
      Identifier: "blog"
      URL: "/post/"

server:
  headers:
  - for: /**
    values:
      Content-Security-Policy: base-uri 'none'; form-action 'none'; default-src 'none'; img-src 'self'; manifest-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'
